### ISSUE TITLE
Check for `required` input

### ISSUE THREAD

**Issue by Link2Twenty** [caribouflex/caribou-stepper#3]
It would be nice if it checked to see if there were any inputs on the current step that were required but blank before it let you move on.

Thanks for the element 🙂

**Comment by caribouflex** [comment]
It can be a good idea. 
I may include it in the default validation function. 
However if someone override it for his own validation he will have to do it himself.

And you're welcome, don't hesitate to tell me about issues and enhancement. Thanks.
